---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 5
    schedule:
      interval: monthly
      day: wednesday
  - package-ecosystem: docker
    directory: .
    open-pull-requests-limit: 5
    schedule:
      interval: monthly
      day: wednesday
  - package-ecosystem: npm
    directory: .
    open-pull-requests-limit: 5
    schedule:
      interval: monthly
      day: wednesday
